name: Unit Testing
on: push
jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '15'
      - name: Install modules
        run: npm ci
      - name: Run tests
        run: npm test
